import { BRAND, BRAND_RGB } from "../../styles/brandTokens";

export const L = {
  bg: BRAND.authPrimaryNavy,
  bgSecondary: BRAND.authDarkBlue,
  bgCard: BRAND.authCardBackground,
  border: BRAND.authBorder,
  primary: BRAND.brandCyan,
  primarySecondary: BRAND.brandSecondaryBlue,
  primaryLight: BRAND.brandLightBlue,
  text: BRAND.white,
  textMuted: BRAND.authLightBlue,
  textLight: BRAND.authLightBlue,
  accentSoft: `rgba(${BRAND_RGB.brandCyan}, 0.12)`,
  accentBorder: `rgba(${BRAND_RGB.brandCyan}, 0.35)`,
  accentMuted: `rgba(${BRAND_RGB.brandCyan}, 0.08)`,
  gradientButton: BRAND.gradientPrimary,
  gradientHighlight: BRAND.gradientPrimary,
  hoverGlow: `rgba(${BRAND_RGB.brandCyan}, 0.25)`,
  shadow: "0 1px 3px rgba(0, 0, 0, 0.2), 0 8px 32px rgba(42, 164, 201, 0.08)",
  shadowHover: "0 4px 16px rgba(0, 0, 0, 0.25), 0 16px 48px rgba(42, 164, 201, 0.18)",
  glassCard: "rgba(23, 59, 94, 0.72)",
  badgeBg: `rgba(${BRAND_RGB.brandCyan}, 0.14)`,
  badgeText: BRAND.brandSecondaryBlue,
  navBg: `rgba(${BRAND_RGB.authPrimaryNavy}, 0.88)`,
  gridLine: `rgba(${BRAND_RGB.brandCyan}, 0.06)`,
  lightBg: BRAND.surface,
  lightText: BRAND.textPrimary,
  lightTextMuted: BRAND.textMuted,
  lightDivider: `rgba(${BRAND_RGB.brandNavy}, 0.12)`,
  lightIconBg: `rgba(${BRAND_RGB.brandCyan}, 0.10)`,
  lightShadow: "0 4px 24px rgba(18, 52, 88, 0.06), 0 1px 3px rgba(18, 52, 88, 0.04)",
  lightBorder: `rgba(${BRAND_RGB.brandNavy}, 0.08)`,
  cardShadow: "0 8px 24px rgba(18, 52, 88, 0.12)",
  cardShadowHover: "0 12px 32px rgba(0, 0, 0, 0.08)",
  sectionSoftBg: BRAND.background,
  sectionHeading: BRAND.brandNavy,
  sectionBody: BRAND.textSecondary,
  challengeTitle: BRAND.brandNavy,
  challengeBody: BRAND.textSecondary,
  challengeBadgeBg: BRAND.amberSoft,
  challengeBadgeText: BRAND.warning,
  challengeIconBg: "rgba(245, 158, 11, 0.14)",
  challengeCardShadow: "0 10px 28px rgba(18, 52, 88, 0.08)",
  solutionBannerBg: BRAND.brandNavy,
  solutionIconBg: `rgba(${BRAND_RGB.brandCyan}, 0.16)`,
  solutionIconColor: BRAND.brandSecondaryBlue,
  solutionLabel: BRAND.brandSecondaryBlue,
  journeyBody: BRAND.textSecondary,
  journeyCardBorder: `rgba(${BRAND_RGB.brandCyan}, 0.18)`,
  journeyCardGlow: `rgba(${BRAND_RGB.brandCyan}, 0.18)`,
  journeyFloatShadow: "0 24px 48px rgba(18, 52, 88, 0.14), 0 8px 24px rgba(42, 164, 201, 0.08)",
  journeyFloatShadowHover: "0 32px 64px rgba(18, 52, 88, 0.18), 0 12px 32px rgba(42, 164, 201, 0.14)",
  modulesBody: BRAND.textSecondary,
  modulesCardBorder: `rgba(${BRAND_RGB.brandCyan}, 0.10)`,
  modulesCardShadow: "0 12px 40px rgba(18, 52, 88, 0.08)",
  modulesCardShadowHover: "0 16px 48px rgba(18, 52, 88, 0.12)",
  modulesHoverBg: BRAND.brandSoft,
};

export const NAV_LINKS = [
  { label: "Home", href: "#home" },
  { label: "Features", href: "#features" },
  { label: "How It Works", href: "#how-it-works" },
  { label: "AI Solutions", href: "#ai-solutions" },
  { label: "Who It's For", href: "#who-its-for" },
  { label: "About", href: "#about" },
  { label: "FAQ", href: "#faq" },
  { label: "Join Us", href: "#join-us" },
];

export const SCROLL_SPY_HREFS = [
  "#home",
  "#who-its-for",
  "#how-it-works",
  "#features",
  "#ai-solutions",
  "#about",
  "#faq",
  "#join-us",
];
