export const ADMIN_NAV_ITEMS = [
  { id: "dashboard", label: "Dashboard", icon: "dashboard" },
  { id: "users", label: "Users", icon: "users" },
  { id: "patients", label: "Patients", icon: "patients" },
  { id: "patientAssignments", label: "Patient Assignments", icon: "patientAssignments" },
  { id: "caseRequests", label: "Case Requests", icon: "caseRequests" },
  { id: "complaints", label: "Complaints", icon: "complaints" },
  { id: "exercises", label: "Exercises", icon: "exercises" },
  { id: "sessions", label: "Sessions", icon: "sessions" },
  { id: "reports", label: "Reports", icon: "reports" },
  { id: "aiCenter", label: "AI Center", icon: "aiCenter" },
  { id: "auditLogs", label: "Audit Logs", icon: "auditLogs" },
  { id: "notifications", label: "Notifications", icon: "notifications" },
  { id: "profile", label: "Profile", icon: "profile" },
];
