import {
  applyReportDetailLocalization,
  applyReportListItemLocalization,
  buildReportFilterOptions,
  formatReportDateLabel,
  getReportDisplayTitle,
  getReportFilterLabel,
  getReportPdfReadyLabel,
  getReportSectionTitleLabel,
  getReportTypeBadgeLabel,
  getReportTypeDisplayLabel,
  getReportsEmptyMessage,
} from "../../specialist-dashboard/utils/specialistReportsLocalization.js";

function translateKey(t, key, fallback, params) {
  if (typeof t === "function") {
    const translated = t(key, params);
    if (translated && translated !== key) {
      return translated;
    }
  }

  if (params && typeof fallback === "string") {
    return Object.entries(params).reduce(
      (result, [name, value]) => result.replace(`{${name}}`, String(value)),
      fallback,
    );
  }

  return fallback;
}

export {
  buildReportFilterOptions,
  getReportFilterLabel,
  getReportTypeDisplayLabel,
  getReportDisplayTitle,
  getReportTypeBadgeLabel,
  getReportPdfReadyLabel,
  getReportSectionTitleLabel,
  formatReportDateLabel,
  getReportsEmptyMessage,
};

export function getAdminReportsLabels(t = null) {
  return {
    title: translateKey(t, "admin.reports.title", "Reports"),
    subtitle: translateKey(
      t,
      "admin.reports.subtitle",
      "Review patient progress and AI-generated clinical reports.",
    ),
    toolbarAriaLabel: translateKey(t, "admin.reports.toolbarAriaLabel", "Reports toolbar"),
    searchAriaLabel: translateKey(t, "admin.reports.searchAriaLabel", "Search reports"),
    searchPlaceholder: translateKey(t, "admin.reports.searchPlaceholder", "Search reports"),
    filterAriaLabel: translateKey(t, "admin.reports.filterAriaLabel", "Report filters"),
    gridAriaLabel: translateKey(t, "admin.reports.gridAriaLabel", "Reports list"),
    viewReport: translateKey(t, "admin.reports.viewReport", "View Report"),
    viewDetails: translateKey(t, "admin.reports.viewDetails", "View Details"),
    loading: translateKey(t, "admin.reports.loading", "Loading reports..."),
    empty: translateKey(
      t,
      "admin.reports.empty",
      "No reports have been generated yet.",
    ),
    emptyFiltered: translateKey(
      t,
      "admin.reports.emptyFiltered",
      "No reports match your search or filter.",
    ),
    loadFailed: translateKey(t, "admin.reports.loadFailed", "Failed to load reports."),
    clearFilters: translateKey(t, "admin.reports.clearFilters", "Clear filters"),
    aiLoadWarning: translateKey(
      t,
      "admin.reports.aiLoadWarning",
      "Some AI reports could not be loaded.",
    ),
    retry: translateKey(t, "common.retry", "Retry"),
    back: translateKey(t, "admin.reports.back", "Back to Reports"),
    detailsTitle: translateKey(t, "admin.reports.detailsTitle", "Report Details"),
    loadingDetails: translateKey(t, "admin.reports.loadingDetails", "Loading report..."),
    notFound: translateKey(t, "admin.reports.notFound", "Report not found."),
    invalidSource: translateKey(t, "admin.reports.invalidSource", "Invalid report source."),
    patient: translateKey(t, "admin.reports.patient", "Patient"),
    specialist: translateKey(t, "admin.reports.specialist", "Specialist"),
    generatedBy: translateKey(t, "admin.reports.generatedBy", "Generated By"),
    reportType: translateKey(t, "admin.reports.reportType", "Report Type"),
    date: translateKey(t, "admin.reports.date", "Date"),
    createdDate: translateKey(t, "admin.reports.createdDate", "Created Date"),
    period: translateKey(t, "admin.reports.period", "Period"),
    periodRange: translateKey(t, "admin.reports.periodRange", "Period: {start} – {end}"),
    summary: translateKey(t, "admin.reports.summary", "Summary"),
    aiSummary: translateKey(t, "admin.reports.aiSummary", "AI Summary"),
    noSummary: translateKey(t, "admin.reports.noSummary", "No summary available."),
    progress: translateKey(t, "admin.reports.progress", "Progress"),
    recommendations: translateKey(t, "admin.reports.recommendations", "Recommendations"),
    pdf: translateKey(t, "admin.reports.pdf", "PDF"),
    attachment: translateKey(t, "admin.reports.attachment", "Attachment"),
    attachments: translateKey(t, "admin.reports.attachments", "Attachments"),
    reportInformation: translateKey(t, "admin.reports.reportInformation", "Report Information"),
    status: translateKey(t, "admin.reports.status", "Status"),
    pdfActionsTitle: translateKey(t, "admin.reports.pdfActionsTitle", "PDF Actions"),
    pdfReport: translateKey(t, "admin.reports.pdfReport", "PDF report"),
    pdfUnavailable: translateKey(t, "admin.reports.pdfUnavailable", "PDF attachment is unavailable."),
    pdfLinkUnavailable: translateKey(
      t,
      "admin.reports.pdfLinkUnavailable",
      "PDF link is unavailable.",
    ),
    pdfActions: {
      viewPdf: translateKey(t, "admin.reports.pdfActions.viewPdf", "View PDF"),
      viewPdfAria: translateKey(t, "admin.reports.pdfActions.viewPdfAria", "View PDF report"),
      generatePdf: translateKey(t, "admin.reports.pdfActions.generatePdf", "Generate PDF"),
      generating: translateKey(t, "admin.reports.pdfActions.generating", "Generating..."),
      copyLink: translateKey(t, "admin.reports.pdfActions.copyLink", "Copy Link"),
      copyPdfLink: translateKey(t, "admin.reports.pdfActions.copyPdfLink", "Copy PDF Link"),
      pdfReady: translateKey(t, "specialist.reports.status.pdfReady", "PDF Ready"),
      linkCopied: translateKey(t, "admin.reports.pdfActions.linkCopied", "Link copied."),
      copyFailed: translateKey(t, "admin.reports.pdfActions.copyFailed", "Unable to copy link."),
      openFailed: translateKey(t, "admin.reports.pdfActions.openFailed", "Unable to open PDF."),
      generateFailed: translateKey(
        t,
        "admin.reports.pdfActions.generateFailed",
        "Failed to generate PDF.",
      ),
      generatedSuccess: translateKey(
        t,
        "admin.reports.pdfActions.generatedSuccess",
        "PDF generated successfully.",
      ),
    },
    toast: {
      detailsLoadFailed: translateKey(
        t,
        "admin.reports.toast.detailsLoadFailed",
        "Failed to load report details.",
      ),
    },
    emptyDisplay: translateKey(t, "parent.common.emptyDisplay", "—"),
  };
}

export function buildAdminReportFilterOptions(t = null) {
  return buildReportFilterOptions(t);
}

export function applyAdminReportLocalization(report, context = {}) {
  if (!report) {
    return report;
  }

  const normalized = {
    ...report,
    isAi: report.isAi ?? report.isAiReport ?? false,
    reportType: report.reportType ?? report.type,
    date: report.date ?? report.createdAt ?? report.generatedAt,
    isPdfReady: report.isPdfReady ?? report.hasPdf ?? false,
  };

  return applyReportListItemLocalization(normalized, context);
}

export function applyAdminReportsLocalization(reports, context = {}) {
  if (!Array.isArray(reports)) {
    return [];
  }

  return reports.map((report) => applyAdminReportLocalization(report, context));
}

export function applyAdminReportDetailsLocalization(detail, context = {}) {
  if (!detail) {
    return detail;
  }

  const normalized = {
    ...detail,
    isAi: detail.isAi ?? detail.isAiReport ?? false,
    reportType: detail.reportType ?? detail.type,
    date: detail.date ?? detail.createdAt ?? detail.generatedAt,
    isPdfReady: detail.isPdfReady ?? detail.hasPdf ?? false,
  };

  return applyReportDetailLocalization(normalized, context);
}

export function mapAdminReportForLocalization(row) {
  return row;
}
